const mongoose = require('mongoose');

const SystemSettingsSchema = new mongoose.Schema(
  {
    key: {
      type: String,
      default: 'master_config',
      unique: true,
    },
    general: {
      hospitalName: { type: String, default: 'DoseTracker Enterprise Healthcare' },
      tagline: { type: String, default: 'Intelligent Healthcare & Medication Platform' },
      registrationNumber: { type: String, default: 'REG-2026-HC89201' },
      licenseNumber: { type: String, default: 'MED-LIC-990214' },
      gstNumber: { type: String, default: '29ABCDE1234F1Z5' },
      hospitalType: { type: String, default: 'Multi-Specialty Super Hospital' },
      website: { type: String, default: 'https://dosetracker.com' },
      supportEmail: { type: String, default: 'support@dosetracker.com' },
      supportPhone: { type: String, default: '+1 (800) 555-DOSE' },
      emergencyPhone: { type: String, default: '+1 (800) 911-HEAL' },
      address: { type: String, default: '100 Medical Center Parkway' },
      city: { type: String, default: 'San Francisco' },
      state: { type: String, default: 'California' },
      country: { type: String, default: 'United States' },
      postalCode: { type: String, default: '94103' },
      timezone: { type: String, default: 'America/Los_Angeles' },
      currency: { type: String, default: 'USD ($)' },
      businessHours: { type: String, default: 'Mon-Sun: 24/7 Open' },
    },
    authentication: {
      enablePatientRegistration: { type: Boolean, default: true },
      enableDoctorRegistration: { type: Boolean, default: true },
      enableStaffRegistration: { type: Boolean, default: true },
      requireDoctorApproval: { type: Boolean, default: true },
      enableEmailVerification: { type: Boolean, default: true },
      enablePhoneVerification: { type: Boolean, default: false },
      enableOtpLogin: { type: Boolean, default: true },
      enableGoogleLogin: { type: Boolean, default: true },
      enableMicrosoftLogin: { type: Boolean, default: true },
      enableAppleLogin: { type: Boolean, default: false },
      sessionTimeoutMinutes: { type: Number, default: 120 },
      maxLoginAttempts: { type: Number, default: 5 },
      lockoutDurationMinutes: { type: Number, default: 15 },
      captchaEnabled: { type: Boolean, default: false },
    },
    security: {
      twoFactorRequired: { type: Boolean, default: false },
      jwtExpiry: { type: String, default: '7d' },
      refreshTokenExpiry: { type: String, default: '30d' },
      rateLimitRequestsPerMin: { type: Number, default: 100 },
      ipWhitelist: { type: Array, default: [] },
      ipBlacklist: { type: Array, default: [] },
      httpsEnforced: { type: Boolean, default: true },
      sqlInjectionProtection: { type: Boolean, default: true },
      xssProtection: { type: Boolean, default: true },
      csrfProtection: { type: Boolean, default: true },
      promptInjectionProtection: { type: Boolean, default: true },
      auditLoggingEnabled: { type: Boolean, default: true },
    },
    ai: {
      enableAI: { type: Boolean, default: true },
      defaultProvider: { type: String, default: 'gemini' },
      providerPriority: { type: Array, default: ['gemini', 'gpt', 'claude', 'deepseek'] },
      temperature: { type: Number, default: 0.7 },
      maxTokens: { type: Number, default: 1000 },
      dailyTokenLimit: { type: Number, default: 500000 },
      sensitiveDataMasking: { type: Boolean, default: true },
      medicalDisclaimerRequired: { type: Boolean, default: true },
    },
    patient: {
      enableDashboard: { type: Boolean, default: true },
      enableTimeline: { type: Boolean, default: true },
      enablePrescriptionScanner: { type: Boolean, default: true },
      enableAIAssistant: { type: Boolean, default: true },
      enableFamilyMembers: { type: Boolean, default: true },
      enableHealthVault: { type: Boolean, default: true },
      enableQREmergencyCard: { type: Boolean, default: true },
      enableBMLogs: { type: Boolean, default: true },
      enableDigitalConsent: { type: Boolean, default: true },
    },
    doctor: {
      enableSoapNotes: { type: Boolean, default: true },
      enablePrescriptionBuilder: { type: Boolean, default: true },
      enableDrugInteractionChecker: { type: Boolean, default: true },
      enableDoctorCalendar: { type: Boolean, default: true },
      enableVideoConsultation: { type: Boolean, default: true },
      enableAIClinicalAssistant: { type: Boolean, default: true },
    },
    admin: {
      roleManagementEnabled: { type: Boolean, default: true },
      doctorVerificationRequired: { type: Boolean, default: true },
      featureFlagsEnabled: { type: Boolean, default: true },
    },
    medication: {
      reminderSound: { type: String, default: 'chime' },
      lowStockThreshold: { type: Number, default: 5 },
      expiryAlertDays: { type: Number, default: 30 },
      duplicateDetection: { type: Boolean, default: true },
      barcodeSupport: { type: Boolean, default: true },
    },
    appointments: {
      slotDurationMinutes: { type: Number, default: 30 },
      maxBookingDaysAhead: { type: Number, default: 60 },
      rescheduleAllowed: { type: Boolean, default: true },
      cancellationPolicyHours: { type: Number, default: 24 },
    },
    notifications: {
      enableEmailNotifications: { type: Boolean, default: true },
      enableSMSNotifications: { type: Boolean, default: true },
      enableWhatsAppNotifications: { type: Boolean, default: true },
      enablePushNotifications: { type: Boolean, default: true },
      enableEmergencyAlerts: { type: Boolean, default: true },
    },
    email: {
      smtpHost: { type: String, default: 'smtp.dosetracker.com' },
      smtpPort: { type: Number, default: 587 },
      smtpUser: { type: String, default: 'notifications@dosetracker.com' },
      smtpEncryption: { type: String, default: 'TLS' },
      senderName: { type: String, default: 'DoseTracker Health Alerts' },
      senderEmail: { type: String, default: 'no-reply@dosetracker.com' },
    },
    sms: {
      provider: { type: String, default: 'Twilio' },
      senderId: { type: String, default: 'DOSETRK' },
      accountSid: { type: String, default: 'AC_MOCK_TWILIO_SID_2026' },
    },
    whatsapp: {
      businessApiEnabled: { type: Boolean, default: true },
      phoneNumberId: { type: String, default: 'WA_PHONE_ID_99012' },
    },
    billing: {
      enableStripe: { type: Boolean, default: true },
      enableRazorpay: { type: Boolean, default: true },
      currencySymbol: { type: String, default: '$' },
      taxPercentage: { type: Number, default: 5.0 },
    },
    database: {
      databaseType: { type: String, default: 'MongoDB Enterprise' },
      connectionPoolSize: { type: Number, default: 20 },
      autoIndexRebuild: { type: Boolean, default: true },
    },
    backup: {
      autoBackupEnabled: { type: Boolean, default: true },
      backupFrequency: { type: String, default: 'daily' },
      cloudStorageProvider: { type: String, default: 'AWS S3' },
      encryptionEnabled: { type: Boolean, default: true },
    },
    api: {
      apiExplorerEnabled: { type: Boolean, default: true },
      rateLimitRequestsPerMin: { type: Number, default: 120 },
      webhookSignatureSecret: { type: String, default: 'whsec_dosetracker_2026_key' },
    },
    systemHealth: {
      serverUptimePercent: { type: Number, default: 99.98 },
      status: { type: String, default: 'HEALTHY' },
    },
    branding: {
      logoUrl: { type: String, default: '/logo.png' },
      primaryColor: { type: String, default: '#6366f1' },
      secondaryColor: { type: String, default: '#f43f5e' },
    },
    localization: {
      defaultLanguage: { type: String, default: 'en' },
      dateFormat: { type: String, default: 'YYYY-MM-DD' },
      timeFormat: { type: String, default: '12h' },
    },
    performance: {
      redisCacheEnabled: { type: Boolean, default: true },
      cdnEnabled: { type: Boolean, default: true },
      lazyLoadingEnabled: { type: Boolean, default: true },
    },
    maintenance: {
      maintenanceMode: { type: Boolean, default: false },
      maintenanceMessage: { type: String, default: 'System is undergoing scheduled maintenance. Back online shortly.' },
    },
    developer: {
      developerMode: { type: Boolean, default: false },
      debugLogging: { type: Boolean, default: false },
    },
    systemInfo: {
      appVersion: { type: String, default: 'v2.5.0-Enterprise' },
      backendVersion: { type: String, default: 'v2.5.0-Node18' },
      databaseVersion: { type: String, default: 'MongoDB v7.0' },
      licenseType: { type: String, default: 'Enterprise SaaS License (Unlimited Users)' },
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('SystemSettings', SystemSettingsSchema);
